services:
  nats-server:
    image: nats:2.9.25
    ports:
      - 8222:8222

  gateway:
    depends_on:
      - nats-server
    build: ./gateway
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    volumes:
      - ./gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - NATS_SERVERS=${NATS_SERVERS}
      - PORT=${GATEWAY_PORT}

  auth-microservice:
    depends_on:
      - gateway
    build: ./auth-microservice
    volumes:
      - ./auth-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - NATS_SERVERS=${NATS_SERVERS}

  movies-microservice:
    depends_on:
      - gateway
    build: ./movies-microservice
    volumes:
      - ./movies-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - NATS_SERVERS=${NATS_SERVERS}
