services:
  nats-server:
    image: nats:2.9.25
    ports:
      - 8222:8222

  auth-database:
    image: postgres:16.2
    restart: always
    volumes:
      - ./auth-microservice/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=users

  gateway:
    depends_on:
      - nats-server
      - auth-database
    build: ./gateway
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    volumes:
      - ./gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - NATS_SERVERS=${NATS_SERVERS}
      - PORT=${GATEWAY_PORT}

  auth-microservice:
    depends_on:
      - auth-database
      - gateway
    build: ./auth-microservice
    volumes:
      - ./auth-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NATS_SERVERS=${NATS_SERVERS}

  movies-microservice:
    depends_on:
      - gateway
    build: ./movies-microservice
    volumes:
      - ./movies-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - NATS_SERVERS=${NATS_SERVERS}
